dist: trusty
language: node_js
cache: yarn
node_js:
  - '10'
services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-server-dev-11
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - psql -c 'create database universal_login_relayer_test;' -U postgres
install:
  - yarn install
script:
  - scripts/travis.sh
