pull_request_rules:
  - name: automatic merge with 2 approvals
    conditions:
      - "#approved-reviews-by>=2"
      - base=master
      - "status-success~=ci/circleci: *"
    actions:
      merge:
        strict: smart
        method: squash
