version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15
        environment:
          PG_HOST: localhost
          PG_USER: postgres
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test

    steps:
      - checkout
      - run: yarn
      - run: yarn test
  lint:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
workflows:
  version: 2
  universallogin:
    jobs:
      - lint
      - test

