version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - save_cache:
            key: universal-login-{{ .Environment.CIRCLE_SHA1 }}
            paths:
              - ~/project
  lint_test_contracts_commons_ops:
    docker:
      - image: circleci/node:10.15
    steps:
      - restore_cache:
            keys:
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn lint
      - run: cd universal-login-contracts && yarn test:nobuild
      - run: cd universal-login-commons && yarn test
      - run: cd universal-login-ops && yarn test
      - run: yarn codechecks
  test_sdk_relayer:
    docker:
      - image: circleci/node:10.15
        environment:
          PG_HOST: localhost
          PG_USER: postgres
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - restore_cache:
            keys:
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd universal-login-sdk && yarn test:nobuild
      - run: cd universal-login-relayer && yarn test:nobuild
  test_react_wallet:
    docker:
      - image: circleci/node:10.15
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: universal_login_relayer_test
    steps:
      - restore_cache:
            keys:
                - universal-login-{{ .Environment.CIRCLE_SHA1 }}
      - run: cd universal-login-react && yarn test
      - run: cd universal-login-wallet && yarn test

workflows:
  version: 2
  universal_login_all:
    jobs:
      - build
      - lint_test_contracts_commons_ops:
          requires:
            - build
      - test_sdk_relayer:
          requires:
            - build
      - test_react_wallet:
          requires:
            - build
