name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cd universal-login-commons
      - name: ESLint Action
        uses: hallee/eslint-action@1.0.1
